<a href="https://colab.research.google.com/github/Manu-Sanchez/Learning/blob/ai%2Fbasic-gan/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
  import numpy as np


In [ ]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Gives 20 numbers between 0 and 10 (linear space)
np.linspace(0, 10, 20)


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(1) #1 number between 0 and 1
np.random.rand(4) #4 numbers between 0 and 1

np.random.randn(10) #Random distribution mean of 0

np.random.randint(1,100,10) #10 random numbers between [1, 100[
np.random.seed(42) #Specify random seed

np.arange(25) #Get numbers between [0, 25[

np.arange(10).reshape(5,2)

np.arange(10).min() #Min value
np.arange(10).argmin() #Position of the min value

np.arange(10).dtype #Datatype

dtype('int64')

In [7]:
arr = np.arange(0,10)

print(arr[8])
print(arr[2:6])
print(arr[:5])
print(arr[5:])

print(arr + 100) #Add 100 to each item in the array
print(arr)

8
[2 3 4 5]
[0 1 2 3 4]
[5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr = np.arange(0, 11)
slice_arr = arr[:6]

slice_arr[:] = 99 #It updates also arr as slice_arr is pointing to that one

print(slice_arr)
print(arr)

arr = np.arange(0, 11)
slice_arr = arr.copy()[:6]

slice_arr[:] = 99 #As this is a copy of the original array, it won't be affected

print(slice_arr)
print(arr)

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]
[99 99 99 99 99 99]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
#TWO DIMENSIONAL ARRAYS

arr_2d = np.array([
    [10, 20, 30],
    [2,1,5],
    [20, 10, 20]
])

print(arr_2d)
print(arr_2d.shape)
print(arr_2d[2, 2]) #ROW COLUMN

slice_arr_2d = arr_2d[:, 2]
slice_arr_2d[:] = 99

print(slice_arr_2d)
print(arr_2d)

[[10 20 30]
 [ 2  1  5]
 [20 10 20]]
(3, 3)
20
[99 99 99]
[[10 20 99]
 [ 2  1 99]
 [20 10 99]]


In [23]:
arr = np.arange(0, 11)

print(arr > 4) #True, False of each item

bool_arr = arr > 4
print(arr[bool_arr]) #Only returns true items
print(arr[arr > 4])

[False False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]
